"""
Seed de puzzles basados en Coffee Break Python, NumPy y Pandas
(Christian Mayer — Finxter)

Formato de cada puzzle:
- code_snippet: el código que el usuario debe leer y predecir su output
- correct_output: la respuesta exacta esperada (comparación estricta)
- elo_rating: dificultad inicial calibrada según los libros
- category: python | numpy | pandas
"""

PUZZLES_PYTHON = [
    {
        "title": "Hello World",
        "slug": "hello-world",
        "category": "python",
        "topic": "basics",
        "code_snippet": 'print("Hello World!")',
        "correct_output": "Hello World!",
        "explanation": "print() muestra el string en pantalla. Las comillas no se imprimen.",
        "hint": "¿Qué hace la función print() con las comillas?",
        "elo_rating": 600,
        "finxter_id": 1,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Variables & Float Division",
        "slug": "variables-float-division",
        "category": "python",
        "topic": "variables",
        "code_snippet": "x = 55 / 11\nprint(x)",
        "correct_output": "5.0",
        "explanation": "En Python 3, la división / siempre retorna float. 55/11 = 5.0, no 5.",
        "hint": "¿El operador / en Python 3 retorna int o float?",
        "elo_rating": 625,
        "finxter_id": 315,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Integer Division",
        "slug": "integer-division",
        "category": "python",
        "topic": "arithmetic",
        "code_snippet": "print(13 // 4)\nprint(13 % 4)",
        "correct_output": "3\n1",
        "explanation": "// es división entera (floor). % es módulo (resto). 13 = 4*3 + 1.",
        "hint": "// trunca el decimal. ¿Qué queda al dividir 13 entre 4?",
        "elo_rating": 800,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "List Indexing",
        "slug": "list-indexing",
        "category": "python",
        "topic": "lists",
        "code_snippet": "lst = [1, 2, 3, 4, 5]\nprint(lst[1])\nprint(lst[-1])",
        "correct_output": "2\n5",
        "explanation": "Los índices empiezan en 0. El índice -1 accede al último elemento.",
        "hint": "Python indexa desde 0. ¿Qué hace un índice negativo?",
        "elo_rating": 900,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Slicing Strings",
        "slug": "slicing-strings",
        "category": "python",
        "topic": "strings",
        "code_snippet": 's = "Coffee"\nprint(s[1:4])\nprint(s[:3])',
        "correct_output": "off\nCof",
        "explanation": "s[1:4] extrae índices 1, 2, 3 (no incluye el 4). s[:3] es s[0:3].",
        "hint": "El slicing [a:b] incluye a pero excluye b.",
        "elo_rating": 1000,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Negative Indices",
        "slug": "negative-indices",
        "category": "python",
        "topic": "lists",
        "code_snippet": "lst = [1, 2, 3, 4, 5]\nprint(lst[-2])\nprint(lst[1:-1])",
        "correct_output": "4\n[2, 3, 4]",
        "explanation": "lst[-2] es el penúltimo. lst[1:-1] excluye el primero y el último.",
        "hint": "Los índices negativos cuentan desde el final.",
        "elo_rating": 1100,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "The For Loop",
        "slug": "for-loop",
        "category": "python",
        "topic": "loops",
        "code_snippet": "for i in range(3):\n    print(i * 2)",
        "correct_output": "0\n2\n4",
        "explanation": "range(3) genera 0, 1, 2. Multiplicados por 2 dan 0, 2, 4.",
        "hint": "range(3) produce 3 valores: ¿cuáles?",
        "elo_rating": 1000,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "String Multiplication",
        "slug": "string-multiplication",
        "category": "python",
        "topic": "strings",
        "code_snippet": 'print("py" * 3)\nprint(len("python"))',
        "correct_output": "pypypy\n6",
        "explanation": "Multiplicar un string repite su contenido. len() cuenta caracteres.",
        "hint": "¿Qué hace el operador * con strings?",
        "elo_rating": 900,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Default Arguments",
        "slug": "default-arguments",
        "category": "python",
        "topic": "functions",
        "code_snippet": "def greet(name, msg='Hello'):\n    print(msg, name)\n\ngreet('Alice')\ngreet('Bob', 'Hi')",
        "correct_output": "Hello Alice\nHi Bob",
        "explanation": "Los argumentos con valor por defecto son opcionales. Si no se pasan, usan el valor por defecto.",
        "hint": "¿Qué pasa cuando llamas la función sin el segundo argumento?",
        "elo_rating": 1200,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Lambda Function",
        "slug": "lambda-function",
        "category": "python",
        "topic": "functions",
        "code_snippet": "square = lambda x: x ** 2\nprint(square(4))\nprint(square(3) + square(4))",
        "correct_output": "16\n25",
        "explanation": "Lambda crea funciones anónimas en una línea. x**2 es x al cuadrado.",
        "hint": "3² + 4² = 9 + 16 = ?",
        "elo_rating": 1300,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Indirect Recursion",
        "slug": "indirect-recursion",
        "category": "python",
        "topic": "recursion",
        "code_snippet": "def is_even(n):\n    if n == 0: return True\n    return is_odd(n - 1)\n\ndef is_odd(n):\n    if n == 0: return False\n    return is_even(n - 1)\n\nprint(is_even(4))",
        "correct_output": "True",
        "explanation": "Recursión mutua: is_even(4)→is_odd(3)→is_even(2)→is_odd(1)→is_even(0)→True.",
        "hint": "Sigue la cadena de llamadas paso a paso.",
        "elo_rating": 1600,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Bubble Sort",
        "slug": "bubble-sort",
        "category": "python",
        "topic": "algorithms",
        "code_snippet": "def bubble(lst):\n    for i in range(len(lst)-1):\n        for j in range(len(lst)-1-i):\n            if lst[j] > lst[j+1]:\n                lst[j], lst[j+1] = lst[j+1], lst[j]\n    return lst\n\nprint(bubble([3, 1, 2]))",
        "correct_output": "[1, 2, 3]",
        "explanation": "Bubble sort compara pares adyacentes y los intercambia si están desordenados.",
        "hint": "El algoritmo mueve el mayor elemento al final en cada pasada.",
        "elo_rating": 1700,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Unpacking kwargs",
        "slug": "unpacking-kwargs",
        "category": "python",
        "topic": "functions",
        "code_snippet": "def f(**kwargs):\n    for k, v in kwargs.items():\n        print(k, v)\n\nf(a=1, b=2, c=3)",
        "correct_output": "a 1\nb 2\nc 3",
        "explanation": "**kwargs captura argumentos con nombre como un diccionario. .items() itera sus pares.",
        "hint": "kwargs es un diccionario. ¿Cómo iteras un dict?",
        "elo_rating": 1500,
        "source_book": "Coffee Break Python",
    },
    {
        "title": "Fibonacci",
        "slug": "fibonacci-recursive",
        "category": "python",
        "topic": "recursion",
        "code_snippet": "def fib(n):\n    if n <= 1: return n\n    return fib(n-1) + fib(n-2)\n\nfor i in range(6):\n    print(fib(i), end=' ')",
        "correct_output": "0 1 1 2 3 5 ",
        "explanation": "Fibonacci: cada número es la suma de los dos anteriores. fib(0)=0, fib(1)=1.",
        "hint": "Calcula fib(0) hasta fib(5) paso a paso.",
        "elo_rating": 1400,
        "source_book": "Coffee Break Python",
    },
]

PUZZLES_NUMPY = [
    {
        "title": "Array Dimensionality",
        "slug": "numpy-array-dimensionality",
        "category": "numpy",
        "topic": "arrays",
        "code_snippet": "import numpy as np\na = np.array([[1, 2], [3, 4], [5, 6]])\nprint(a.ndim)\nprint(a.shape)",
        "correct_output": "2\n(3, 2)",
        "explanation": "ndim es el número de dimensiones. shape retorna una tupla (filas, columnas).",
        "hint": "¿Cuántas filas y columnas tiene la matriz?",
        "elo_rating": 1100,
        "is_advanced": True,
        "source_book": "Coffee Break NumPy",
    },
    {
        "title": "Accessing Array Shape",
        "slug": "numpy-array-shape",
        "category": "numpy",
        "topic": "arrays",
        "code_snippet": "import numpy as np\ndataScientist = [133, 132, 137]\nproductManager = [127, 140, 145]\na = np.array([dataScientist, productManager])\nprint(a.shape[0])\nprint(a.shape[1])",
        "correct_output": "2\n3",
        "explanation": "shape[0] = número de filas (2 trabajos). shape[1] = número de columnas (3 años).",
        "hint": "shape es (filas, columnas). ¿Cuántas filas tiene este array?",
        "elo_rating": 1200,
        "is_advanced": True,
        "finxter_id": 412,
        "source_book": "Coffee Break NumPy",
    },
    {
        "title": "Boolean Indexing",
        "slug": "numpy-boolean-indexing",
        "category": "numpy",
        "topic": "indexing",
        "code_snippet": "import numpy as np\na = np.array([10, 20, 30, 40, 50])\nprint(a[a > 25])",
        "correct_output": "[30 40 50]",
        "explanation": "a > 25 crea una máscara booleana. Usarla como índice filtra solo los True.",
        "hint": "¿Qué valores son mayores que 25?",
        "elo_rating": 1400,
        "is_advanced": True,
        "source_book": "Coffee Break NumPy",
    },
    {
        "title": "Broadcasting",
        "slug": "numpy-broadcasting",
        "category": "numpy",
        "topic": "operations",
        "code_snippet": "import numpy as np\na = np.array([[1, 2, 3], [4, 5, 6]])\nprint(a + 10)",
        "correct_output": "[[11 12 13]\n [14 15 16]]",
        "explanation": "Broadcasting suma el escalar 10 a cada elemento del array.",
        "hint": "NumPy aplica la operación a todos los elementos automáticamente.",
        "elo_rating": 1300,
        "is_advanced": True,
        "source_book": "Coffee Break NumPy",
    },
    {
        "title": "Cumulative Sum",
        "slug": "numpy-cumsum",
        "category": "numpy",
        "topic": "statistics",
        "code_snippet": "import numpy as np\na = np.array([1, 2, 3, 4])\nprint(np.cumsum(a))",
        "correct_output": "[ 1  3  6 10]",
        "explanation": "cumsum calcula sumas acumulativas: [1, 1+2, 1+2+3, 1+2+3+4].",
        "hint": "Cada elemento es la suma de todos los anteriores más el actual.",
        "elo_rating": 1500,
        "is_advanced": True,
        "source_book": "Coffee Break NumPy",
    },
]

PUZZLES_PANDAS = [
    {
        "title": "Series Creation",
        "slug": "pandas-series-creation",
        "category": "pandas",
        "topic": "series",
        "code_snippet": "import pandas as pd\ns = pd.Series([10, 20, 30], index=['a', 'b', 'c'])\nprint(s['b'])\nprint(s[1])",
        "correct_output": "20\n20",
        "explanation": "Una Series es como un diccionario ordenado. Puedes indexar por etiqueta o posición.",
        "hint": "'b' es la etiqueta del índice 1. Ambos acceden al mismo elemento.",
        "elo_rating": 1200,
        "is_advanced": True,
        "source_book": "Coffee Break Pandas",
    },
    {
        "title": "DataFrame Shape",
        "slug": "pandas-dataframe-shape",
        "category": "pandas",
        "topic": "dataframe",
        "code_snippet": "import pandas as pd\ndf = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6], 'C': [7,8,9]})\nprint(df.shape)\nprint(len(df.columns))",
        "correct_output": "(3, 3)\n3",
        "explanation": "shape retorna (filas, columnas). len(df.columns) cuenta las columnas.",
        "hint": "¿Cuántas filas y columnas tiene este DataFrame?",
        "elo_rating": 1100,
        "is_advanced": True,
        "source_book": "Coffee Break Pandas",
    },
    {
        "title": "Boolean Filtering",
        "slug": "pandas-boolean-filtering",
        "category": "pandas",
        "topic": "filtering",
        "code_snippet": "import pandas as pd\ndf = pd.DataFrame({'name': ['Alice','Bob','Carol'], 'age': [25, 30, 22]})\nprint(df[df['age'] > 24]['name'].values)",
        "correct_output": "['Alice' 'Bob']",
        "explanation": "df[condition] filtra filas. .values retorna un array NumPy con los valores.",
        "hint": "¿Qué edades son mayores que 24?",
        "elo_rating": 1400,
        "is_advanced": True,
        "source_book": "Coffee Break Pandas",
    },
]

ALL_PUZZLES = PUZZLES_PYTHON + PUZZLES_NUMPY + PUZZLES_PANDAS
