"""0001_initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-05-06 17:28:17.751012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coding_challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("source_path", sa.String(length=500), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("starter_code", sa.Text(), nullable=False),
        sa.Column("reference_solution", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coding_challenges_difficulty"),
        "coding_challenges",
        ["difficulty"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coding_challenges_id"), "coding_challenges", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_coding_challenges_slug"), "coding_challenges", ["slug"], unique=True
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("estimated_duration", sa.Integer(), nullable=True),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_id"), "lessons", ["id"], unique=False)
    op.create_table(
        "puzzles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.Column("code_snippet", sa.Text(), nullable=False),
        sa.Column("correct_output", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("elo_rating", sa.Integer(), nullable=False),
        sa.Column("elo_initial", sa.Integer(), nullable=False),
        sa.Column("times_attempted", sa.Integer(), nullable=False),
        sa.Column("times_correct", sa.Integer(), nullable=False),
        sa.Column("is_advanced", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("finxter_id", sa.Integer(), nullable=True),
        sa.Column("source_book", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_puzzles_id"), "puzzles", ["id"], unique=False)
    op.create_index(op.f("ix_puzzles_slug"), "puzzles", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("starter_code", sa.Text(), nullable=True),
        sa.Column("solution_code", sa.Text(), nullable=True),
        sa.Column("test_cases", sa.JSON(), nullable=True),
        sa.Column("hints", sa.JSON(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.String(length=50), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_id"), "exercises", ["id"], unique=False)
    op.create_table(
        "puzzle_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("puzzle_id", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("user_answer", sa.Text(), nullable=True),
        sa.Column("user_elo_before", sa.Integer(), nullable=False),
        sa.Column("user_elo_after", sa.Integer(), nullable=False),
        sa.Column("puzzle_elo_before", sa.Integer(), nullable=False),
        sa.Column("puzzle_elo_after", sa.Integer(), nullable=False),
        sa.Column("elo_delta_user", sa.Integer(), nullable=False),
        sa.Column("elo_delta_puzzle", sa.Integer(), nullable=False),
        sa.Column("expected_probability", sa.Float(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["puzzle_id"],
            ["puzzles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_puzzle_attempts_id"), "puzzle_attempts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_puzzle_attempts_puzzle_id"),
        "puzzle_attempts",
        ["puzzle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_puzzle_attempts_user_id"), "puzzle_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "tutor_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.Column("messages", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=True),
        sa.Column("xp_points", sa.Integer(), nullable=True),
        sa.Column("badges", sa.Text(), nullable=True),
        sa.Column("preferences", sa.Text(), nullable=True),
        sa.Column("elo_rating", sa.Integer(), nullable=False),
        sa.Column("elo_peak", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(length=50), nullable=False),
        sa.Column("puzzles_attempted", sa.Integer(), nullable=False),
        sa.Column("puzzles_correct", sa.Integer(), nullable=False),
        sa.Column("streak_current", sa.Integer(), nullable=False),
        sa.Column("streak_best", sa.Integer(), nullable=False),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "user_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("time_spent", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("message_index", sa.Integer(), nullable=False),
        sa.Column("helpful_rating", sa.Integer(), nullable=True),
        sa.Column("feedback_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["tutor_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "code_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("result", sa.String(length=50), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("execution_time", sa.Integer(), nullable=True),
        sa.Column("passed_tests", sa.Integer(), nullable=True),
        sa.Column("total_tests", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "elo_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_profile_id", sa.Integer(), nullable=False),
        sa.Column("puzzle_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("elo_value", sa.Integer(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("rank_label", sa.String(length=50), nullable=False),
        sa.Column("puzzle_title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["puzzle_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["puzzle_id"],
            ["puzzles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_elo_history_id"), "elo_history", ["id"], unique=False)
    op.create_index(
        op.f("ix_elo_history_user_profile_id"),
        "elo_history",
        ["user_profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_elo_history_user_profile_id"), table_name="elo_history")
    op.drop_index(op.f("ix_elo_history_id"), table_name="elo_history")
    op.drop_table("elo_history")
    op.drop_table("code_submissions")
    op.drop_table("ai_feedback")
    op.drop_table("user_progress")
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_table("tutor_sessions")
    op.drop_index(op.f("ix_puzzle_attempts_user_id"), table_name="puzzle_attempts")
    op.drop_index(op.f("ix_puzzle_attempts_puzzle_id"), table_name="puzzle_attempts")
    op.drop_index(op.f("ix_puzzle_attempts_id"), table_name="puzzle_attempts")
    op.drop_table("puzzle_attempts")
    op.drop_index(op.f("ix_exercises_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_puzzles_slug"), table_name="puzzles")
    op.drop_index(op.f("ix_puzzles_id"), table_name="puzzles")
    op.drop_table("puzzles")
    op.drop_index(op.f("ix_lessons_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_coding_challenges_slug"), table_name="coding_challenges")
    op.drop_index(op.f("ix_coding_challenges_id"), table_name="coding_challenges")
    op.drop_index(
        op.f("ix_coding_challenges_difficulty"), table_name="coding_challenges"
    )
    op.drop_table("coding_challenges")
    # ### end Alembic commands ###
